- name: Run my new module in my new collection
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Run my_module via a collection
      rhtr.my_collection.my_module:
        data: hello rhtr
      register: r_my_module

    - name: display output to terminal window
      debug:
        var: r_my_module
